# --- .github/workflows/ci.yml ---

name: C++ CI

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Use the latest version of Ubuntu for the virtual machine
    runs-on: ubuntu-latest

    steps:
    # 1. Check out your repository's code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Set up Python, which is needed to run Conan
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. Install and configure Conan
    - name: Install and configure Conan
      run: |
        pip install conan
        conan profile detect --force

    # 4. Run Conan to install dependencies
    - name: Install dependencies
      run: conan install . --profile:host=default --build=missing

    # 5. Configure the CMake project
    - name: Configure CMake
      run: cmake --preset conan-debug
      
    # 6. Build the project (including tests)
    - name: Build
      run: cmake --build --preset conan-debug

    # 7. Run the tests using CTest
    - name: Run tests
      working-directory: ./build/debug
      run: ctest --output-on-failure
